### ISSUE TITLE
defaults in gitup.conf and gitup.conf.sample

### ISSUE THREAD

**Issue by grahamperrin** [johnmehr/gitup#77]
With a fresh installation: 

![image](https://user-images.githubusercontent.com/192271/158000837-b7329515-3d47-47ec-a8d4-48bc56cfb199.png)

* stable/12 by default
* stable/13 might be better. 

----

Side note: <https://forums.freebsd.org/posts/559707>

> By the way, a freshly upgraded stable/13 system now labels itself 13.1-STABLE.

**Comment by johnmehr** [comment]
I just sent an email to the port maintainer asking if the code in net/svnup that automatically updates the config file's default OS version to match the computer's OS version can be copied over to net/gitup.  Thanks!

**Comment by grahamperrin** [comment]
Thanks. 

https://github.com/johnmehr/gitup/commit/25198561b67b14b3b6b16b4cc82e0d0635a882d2#diff-39bd767a59a3138594332fbe99b51c0e531831ee92817e389b3435e1dd1474f9R51

* was for `stable/12`

https://github.com/johnmehr/gitup/commit/25198561b67b14b3b6b16b4cc82e0d0635a882d2#diff-39bd767a59a3138594332fbe99b51c0e531831ee92817e389b3435e1dd1474f9R36

* was for `releng/11.4`

– the configuration file(s) can be updated to `releng/13.1`, soon.

<https://www.freebsd.org/releases/13.1R/schedule/>

**Comment by nunotexbsd** [comment]
net/svnup uses a reinplace command to automate stable and releng in config file but it fails when user is using CURRENT because it gives stable/14 and releng/14.0. I really like this automation but it must be fixed to CURRENT to avoid results like:
---
[release]
branch=base/releng/14.0
target=/usr/src
...
[stable]
branch=base/stable/14
target=/usr/src
---
IMO gitup config should always be an example and then user should track whatever he wants, stable or release or current.

My question is, what results should gitup.conf for CURRENT users?
---
[release]
branch=NULL
target=/usr/src
...
[stable]
branch=NULL
target=/usr/src
---

**Comment by grahamperrin** [comment]
Automation will be nice, but for now (without too much delay), can the port be updated in a simple way? 

For `gitup.conf` to have, at least, `13.1` in lieu of `11.4` for `release`. 

Thanks

**Comment by johnmehr** [comment]
I updated it to 12.3 but it looks like I neglected to commit it.  :(

Until the automation is implemented, I'd like to use the oldest supported version, assuming it has the largest number of deployed instances.  Do you know of any stats out there that show the percentage breakdown of the currently supported versions deployed in the world?   

@nunotexbsd, do you know if there has been any progress in reusing the code that Jason implemented for svnup?  Thanks!

**Comment by nunotexbsd** [comment]
Hello,

The problem is that svnup automation doesn't work correctly on CURRENT
svnup.conf:
`[release]
branch=base/releng/14.0 [1]
target=/usr/src

[ports]
branch=ports/head
target=/usr/ports

[stable]
branch=base/stable/14 [2]
target=/usr/src`

[1][2] neither releng 14.0 or stable 14 exists

I've talked with Jason about doing some adjustments but still nothing

**Comment by nunotexbsd** [comment]
Hello,

[Commit](https://cgit.freebsd.org/ports/commit/?id=f92998df01d6e5402d31fff7010bb477d66b1137) done.

I've done interactive poudriere tests with 12.3 and 13.1 with success, automation works accordingly with those versions.

I'm thinking in a 'if ${OSREL}' condition == 14.0 to give a solution for CURRENT, well it's easy to implement but I don't know what to put into 'releng' and 'stable' :)

Cheers

**Comment by johnmehr** [comment]
This should be implemented now.  Thank you!
